services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: apigateway
    container_name: api-gateway
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ProductService__BaseUrl: "http://product-service:8080"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
    depends_on:
      - product-service
      - rabbitmq
    networks:
      - microservices-net

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: productservice
    container_name: product-service
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
    depends_on:
      - rabbitmq
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # conexión interna
      - "15672:15672" # panel web
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
